# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a14bb0ac95a2a79fddbe5c23a087830aed23e76279a5ab36510b6a432c192f123984f00073bfd2fa09708da6d9f63a6b74ba72fa32d446cfe87b6dfc2e1f005

test:
  secret_key_base: 8b00e096b7c5c439d315b3da69802da022137dd7444fd89090f3aa8c6c02db509ec634336462328ec9e3d745aa829ee98c6d6f7060e2f1ba15ca91af1d0e5992

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
